export const ProtoEnum = Object.freeze({"HTTP":1, "HTTPS":2, "UNKNOWN":3});

export const TOGGLE_POLICY1 = "TOGGLE_POLICY1"
export const TOGGLE_POLICY2 = "TOGGLE_POLICY2"
export const TOGGLE_POLICY3 = "TOGGLE_POLICY3"
export const TOGGLE_POLICY4 = "TOGGLE_POLICY4"

export const SET_BEFORE_AFTER_POLICY1 = "SET_BEFORE_AFTER_POLICY1"
export const SET_BEFORE_AFTER_POLICY2 = "SET_BEFORE_AFTER_POLICY2"
export const SET_BEFORE_AFTER_POLICY3 = "SET_BEFORE_AFTER_POLICY3"
export const SET_BEFORE_AFTER_POLICY4 = "SET_BEFORE_AFTER_POLICY4"

export const ADD_REQUEST = "ADD_REQUEST"
export const SELECT_REQUEST = "SELECT_REQUEST"
